apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-keybridge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:ak1922/argoos.git
    targetRevision: HEAD
    path: keybridge/argofiles
  destination:
    server: https://kmaster:6443
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
