apiVersion: v1
kind: Service
metadata:
  name: keybridge-svc
  namespace: devops
spec:
  selector:
    app: keybridge
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32010